#!/usr/bin/env python3
"""
build_sheet_check.py  (5.02.00)

Lean build-time gate (replaces the hand-written manifest at run_gate). Verifies a
PROJECT BUILD PLACEMENT PACKET ("builder sheet") generated by part_context_resolver:

  COVERAGE   - every ObjectID called in the Python build appears in the sheet.
  POPULATED  - each used part has its resolved mechanical data AND a non-empty
               build_application comment (the AI's note on what the part does here).
  INTEGRITY  - the sheet's mechanical fields still MATCH a fresh resolver run, so the
               AI can only ADD the build_application; it cannot edit tier/methods/etc.
               (tamper-evident; nothing to fabricate because the sheet is generated.)

Usage:
  build_sheet_check.py <script.py> <build_sheet.json> [package_root]
  build_sheet_check.py --self-test
"""
import json,os,sys,re
sys.dont_write_bytecode=True
HERE=os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0,HERE)
import part_context_resolver as PCR

MECH_FIELDS=("governing_precedence_tier","data_backed_tiers","snap","allowed_methods","forbidden","applicable_part_rules","applicable_rule_behaviors")

def used_object_ids(src):
    ids=set(re.findall(r"add_part\(\s*[\"']([A-Z0-9_]+)[\"']",src))
    ids|=set(re.findall(r"\[\"ObjectID\"\]\s*=\s*[\"']([A-Z0-9_]+)[\"']",src))
    m=re.search(r"PART_IDS\s*=\s*\[([^\]]*)\]",src)
    if m: ids|=set(re.findall(r"[\"']([A-Z0-9_]+)[\"']",m.group(1)))
    return {i for i in ids if i not in {"PASS","FAIL","NONE","TRUE","FALSE"}}

def verify(src, sheet, root=None):
    f=[]
    mpc=(sheet.get("MANDATORY_PLACEMENT_CONTEXT",{}) or {})
    parts=mpc.get("parts",{})
    if not parts: return ["build sheet has no MANDATORY_PLACEMENT_CONTEXT.parts"]
    # Wave 3.1 — build-level assembly recipes must carry actionable behavior + match the resolver
    for b in mpc.get("assembly_rule_behaviors",[]):
        if not str(b.get("required_behavior","")).strip():
            f.append(f"assembly_rule_behaviors has empty required_behavior for {b.get('rule_id')}; add it to data/RUNTIME_BEHAVIORS.json")
    used=used_object_ids(src)
    if not used: f.append("no ObjectIDs found in the Python build to cover")
    # COVERAGE
    for oid in sorted(used):
        if oid not in parts: f.append(f"ObjectID {oid} is used in the Python but has no build-sheet entry (coverage)")
    # fresh resolve for integrity
    try:
        fresh=PCR.resolve(list(parts), sheet.get("build_intent",""), root)["MANDATORY_PLACEMENT_CONTEXT"]["parts"]
    except Exception as e:
        return f+[f"could not re-resolve for integrity check: {e}"]
    for oid,entry in parts.items():
        # POPULATED: application comment non-empty
        if not str(entry.get("build_application","")).strip():
            f.append(f"build_application empty for {oid} (AI must state what this part does in this build)")
        # POPULATED: mechanical data present
        if entry.get("governing_precedence_tier") is None or entry.get("snap") is None:
            f.append(f"build-sheet entry for {oid} is missing resolved mechanical data")
        # Wave 3: every emitted behavior must carry an actionable required_behavior
        for b in entry.get("applicable_rule_behaviors",[]):
            if not str(b.get("required_behavior","")).strip():
                f.append(f"applicable_rule_behaviors for {oid} has empty required_behavior for {b.get('rule_id')}; add it to data/RUNTIME_BEHAVIORS.json")
        # INTEGRITY: mechanical fields unchanged vs fresh resolve
        if oid in fresh:
            for k in MECH_FIELDS:
                if entry.get(k)!=fresh[oid].get(k):
                    f.append(f"build-sheet field '{k}' for {oid} does not match the resolver (edited/stale); regenerate the sheet")
    return f

def _run(src,sheet,root=None):
    fails=verify(src,sheet,root)
    for x in fails: print("  FAIL:",x)
    print("BUILD SHEET CHECK:","FAIL" if fails else "PASS"); return 1 if fails else 0

def _self_test():
    root=os.path.dirname(HERE)
    # generate a real sheet for one snap part + one free part
    snap=sorted(PCR._snap_set(root)); s=snap[0] if snap else "S_WALL_H"
    sheet=PCR.resolve([s,"BILLBOARD"],"self-test enclosure",root)
    # AI fills application comments
    for oid in sheet["MANDATORY_PLACEMENT_CONTEXT"]["parts"]:
        sheet["MANDATORY_PLACEMENT_CONTEXT"]["parts"][oid]["build_application"]="perimeter course"
    good_src=f'PART_IDS=["{s}","BILLBOARD"]\np=add_part("{s}")\nq=add_part("BILLBOARD")\n'
    assert not verify(good_src,sheet,root), ("good should pass",verify(good_src,sheet,root))
    # coverage fail: use an extra uncovered ObjectID
    bad_cov=good_src+'r=add_part("S_FLOOR")\n'
    assert any("coverage" in x for x in verify(bad_cov,sheet,root)), "coverage fail not caught"
    # population fail: empty application
    import copy; sheet2=copy.deepcopy(sheet)
    next(iter(sheet2["MANDATORY_PLACEMENT_CONTEXT"]["parts"].values()))["build_application"]=""
    assert any("build_application empty" in x for x in verify(good_src,sheet2,root)), "empty application not caught"
    # integrity fail: tamper a mechanical field
    sheet3=copy.deepcopy(sheet)
    list(sheet3["MANDATORY_PLACEMENT_CONTEXT"]["parts"].values())[0]["governing_precedence_tier"]=99
    assert any("does not match the resolver" in x for x in verify(good_src,sheet3,root)), "integrity tamper not caught"
    print("BUILD SHEET CHECK SELF-TEST: PASS"); return 0

if __name__=="__main__":
    if len(sys.argv)>=2 and sys.argv[1]=="--self-test": sys.exit(_self_test())
    if len(sys.argv)<3: print("usage: build_sheet_check.py <script.py> <build_sheet.json> [root]"); sys.exit(2)
    src=open(sys.argv[1],encoding="utf-8",errors="ignore").read()
    sheet=json.load(open(sys.argv[2],encoding="utf-8"))
    root=sys.argv[3] if len(sys.argv)>3 else None
    sys.exit(_run(src,sheet,root))
